### PR TITLE
Upgrade syn

### PR DESCRIPTION
**Pull request by mehcode**

### CODE REVIEW

**Comment by mehcode** [comment]
Doesn't seem like Actix uses anything that changed extensively. The syn 0.15 release seems focused around function-like macros (recently stabilized).

**Comment by DoumanAsh** [comment]
Ok, thank you

**Comment by fafhrd91** [comment]
@DoumanAsh could you update changes and make new release?

**Comment by DoumanAsh** [comment]
Done

**Comment by fafhrd91** [comment]
Thanks

**Pull request merged**
